CREATE TABLE IF NOT EXISTS users(
  id         VARCHAR(36) PRIMARY KEY UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name       VARCHAR(150) NOT NULL,
  email      VARCHAR(150) NOT NULL,
  picture    VARCHAR(255) NOT NULL,
  status     SMALLINT DEFAULT 1
);
